@startuml Создание отчета

start

:Выбор типа отчета\nответственным;

switch (Тип отчета)
case (Отчет по\nстатистике)
  if (Есть фильтры?) then (да)
  :Выборка по фильтрам;
  endif
  :Подсчет статистики;
  :Генерация Excel Файла;
  :Запись статистики в файл;
  :Создание диаграмм;
case (Отчет по\nответственному)
  :Поиск текущего ответственного;
  :Выбор данных о\nтекущем ответственном;
  :Создание Word файла;
  :Запись данных в файл;
  :Форматирование текста;
case (Отчет по\nрешению проблемы)
  :Выбор проблемы;
  :Создание Word файла;
  :Запись данных в файл;
  :Форматирование текста;
endswitch

:Сохранение файла;
:Запись файла в БД;
:Вывод пути к файлу;

stop

@enduml