@startuml Прецеденты
left to right direction

actor Работник as W
actor Ответственный as R
actor Админ as A

A <|. R
R <|. W

rectangle "Доска Решения Проблем"{
  W --> (Просмотр проблем)
  (Просмотр проблем) .left.o (Использование фильтров) : extend
  W --> (Создание проблем)
  (Создание проблем) *.. (Указание темы) : include
  (Создание проблем) *.. (Указание участка) : include
  (Создание проблем) *.. (Указание даты и времени) : include
  (Создание проблем) *.. (Ввод описания) : include
  W --> (Просмотр отчетов)

  R --> (Решение проблем)
  (Решение проблем) *.. (Указание даты и времени) : include
  (Решение проблем) *.. (Ввод последовательности решения) : include
  R --> (Создание отчетов)
  (Создание отчетов) *.. (Создание отчета по статистике) : include
  (Создание отчетов) *.. (Создание отчета по решению проблемы) : include
  (Создание отчетов) *.. (Создание отчета по ответственному) : include

  A --> (Изменение данных в БД)
  (Изменение данных в БД) ..o (Изменение таблицы отделов) : extend 
  (Изменение данных в БД) ..o (Изменение таблицы тем) : extend
  (Изменение данных в БД) ..o (Изменение таблицы работников) : extend
  (Изменение данных в БД) ..o (Изменение таблицы проблем) : extend
}
@enduml